"""
Django settings for cloudstorage project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    "django-insecure-v3b61da=1g=_(jv!vlkkgts3#!v0s@e6%d3g#1zmeh^vgj@skz"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0") == "1"

ALLOWED_HOSTS = [
    val.strip() for val in os.getenv("ALLOWED_HOSTS", "").split(",")
]

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "storage.apps.StorageConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "ninja.compatibility.files.fix_request_files_middleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cloudstorage.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cloudstorage.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "cloudstorage",
            "USER": "developer",
            "PASSWORD": "development",
            "HOST": "localhost",
            "PORT": "5432",
            # "OPTIONS": {"sslmode": "require"},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGES = (
    ("en", _("English")),
    ("sw", _("Swahili")),
)  # Completely remove this config to declare all languages

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FILES_ROOT = BASE_DIR / "files"

MEDIA_URL = "/media/"

MEDIA_ROOT = FILES_ROOT / "media"

STATIC_ROOT = FILES_ROOT / "static"

# CLOUDSTORAGE

"""
STORAGES = {
    "default": {
        "BACKEND": "project.storage.CloudStorage",
        "OPTIONS": {
            # optional kwargs for your storage class
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
}
"""

CLOUD_STORAGE_BASE_URL = "http://localhost:8000"
CLOUD_STORAGE_MEDIA_URL = "/media/"
CLOUD_STORAGE_AUTO_DETECT_LOCAL_FILE = True
CLOUD_STORAGE_API_TOKEN = "6631379b-c9e5-4881-92b7-4873d953a1a3"
SITE_ADDRESS = (
    "/"  # You can add acccessible url e.g https://yourdomain.tld
)


JAZZMIN_SETTINGS = {
    "site_title": "Faya Cloud File Storage Admin",
    "site_header": "FayaLLC Cloud",
    "site_brand": "FayaLLC Cloud",
    "welcome_sign": "Welcome to FayaLLC Cloud Storage",
    "copyright": "Faya LLC",
    "site_logo": "storage/img/cloud.png",
    "site_logo_classes": "img-circle",
    "search_model": ["storage.CloudFile"],
    "icons": {
        "auth.User": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-book",
        "users.CustomUser": "fas fa-user",
        "storage.Application": "fa-solid fa-cubes",
        "storage.CloudFile": "fas fa-file-upload",
        "storage.Music": "fas fa-music",
        "auth": "fas fa-users-cog",
    },
    "topmenu_links": [
        {
            "name": "Home",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {"app": "storage"},
        {"model": "storage.CloudFile"},
    ],
    "usermenu_links": [
        {
            "name": "Support",
            "url": "https://github.com/fayallc/cloudstorage",
            "new_window": True,
            "icon": "fa fa-tools",
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["storage", "auth"],
    "theme": "cosmo",
    "custom_css": None,
    "custom_js": None,
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark navbar-primary",
    "sidebar": "sidebar-dark-primary",
    "theme": "cosmo",
    "dark_mode_theme": "cyborg",
    "accent": "accent-info",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_collapse": True,
    "footer_fixed": False,
}
